### ISSUE TITLE
Consider using consistent formatting for .md files

### ISSUE THREAD

**Issue by BenAuerDev** [serverpod/serverpod_docs#100]
I have a markdown linter (DavidAnson.vscode-markdownlint) activated and when opening a .md file in the docs all the yellow can be quite intimidating, plus I can't use format-on-save.

My proposal: Format existing .md files according to markdownlint and require correct formatting like done for dart code.

unformatted:
![unformatted](https://github.com/serverpod/serverpod_docs/assets/136239531/20ec0f55-ce3c-468d-8757-25b4856d9a33)

formatted: 
![formatted](https://github.com/serverpod/serverpod_docs/assets/136239531/80917d02-df2d-4dce-b4ab-e1e84c061e05)

PS: Of course I volunteer for the reformatting :)

**Comment by Isakdl** [comment]
Not a bad idea at all, do you know if there is any CI tool to run the same linting? If we format based on a linter we should also enforce it in each PR created.

Feel free to create a PR with this, but please include a CI job if you do.

**Comment by BenAuerDev** [comment]
Yes there is a CI-tool for it on :) [github-actions-marketplace](https://github.com/marketplace/actions/markdown-lint) 

I'll include it in a job that runs before test-build like:

```yaml
markdown-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run markdownlint
              uses: articulate/actions-markdownlint@v1
              with:
                  config: .markdownlint.json
                  files: './docs/**/*.md'
```

most changes can be done by auto-fix like: trailing white space and missing empty lines

a few things I will have to do manually like: headings jumping from 1 to 3 (# and next ###)  and inline-html 

also I'm straight up disabling a rule that tries to enforce **only 80 signs per line**
